name: genz
version: 3.0.0+10
publish_to: none
description: GenZ Android and iOS app
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.20.0
  firebase_crashlytics: ^3.5.7
  chat_bubbles: ^1.6.0
  google_maps_flutter: ^2.6.1
  url_launcher: ^6.3.0
  file_picker: ^8.0.5
  firebase_storage: ^11.7.7
  uuid: ^4.5.0
  flutter_background_geolocation: ^4.16.0
  geoflutterfire2: ^2.3.15
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  geocoding: ^3.0.0
  flutter_native_splash: ^2.4.0
  firebase_remote_config: ^4.4.7
  purchases_flutter: ^8.1.6
  firebase_messaging: ^14.9.4
  shimmer: ^3.0.0
  cached_network_image: ^3.4.0
  connectivity_plus: ^6.0.5
  image: ^4.2.0
  path_provider: ^2.1.4
  flutter_app_badger: ^1.5.0
  flutter_ringtone_player: ^4.0.0+3

dev_dependencies:
  change_app_package_name: ^1.4.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/locales/
    - assets/images/
# emoji icon source: https://iconduck.com/emojis/126262/peach-emoji

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/startup.png"
