import 'package:flutter/widgets.dart';
import 'package:genz/app/global/colors.dart';

const family = 'Hanken Grotesk';
final features = [FontFeature.stylisticSet(1)];

/// Centralizes all the text styles used in the app
class TextStyles {
  /// The base textStyle predefining the font
  /// family and style preset
  static final base = TextStyle(
    fontFamily: family,
    fontFeatures: features,
  ).copyWith;

  /// Used for texts on the top of the screen
  /// summarizing the destination
  static final pageTitle = base(
    fontSize: 28,
    fontWeight: FontWeight.w700,
    color: AppColors.text,
    height: 1.28,
  );

  static final pageTitle24 = pageTitle.copyWith(
    fontSize: 24,
  );

  static final pageTitle18 = pageTitle.copyWith(
    fontSize: 18,
  );

  /// Most commontly used text style for
  /// information produced by the UI of the app
  static final subtitle = base(
    fontSize: 16,
    fontWeight: FontWeight.w500,
    color: AppColors.secondary,
  );

  /// Part of a [subtitle] used in [TextSpan] to
  /// signal that the text is clickable. Usually
  /// used for links inside the subtitle
  static final subtitleAction = base(
    fontSize: 16,
    fontWeight: FontWeight.w600,
    color: AppColors.text,
  );

  /// Used in text placed inside a bottom button
  /// that usually proceeds to some action and has
  /// the highest emphasis on the screen
  static final action = base(
    fontSize: 18,
    fontWeight: FontWeight.w600,
    color: AppColors.white,
  );

  static final actionText = action.copyWith(
    color: AppColors.text,
  );

  /// Used in text generated by the *user*,
  /// usually thats the text inside a [TextField]
  /// or message bubble texts
  static final standart = base(
    fontSize: 18,
    fontWeight: FontWeight.w500,
    color: AppColors.text,
    height: 24 / 18,
  );

  static final placeholder = standart.copyWith(
    color: AppColors.text.withOpacity(0.5),
    //make single line
    overflow: TextOverflow.ellipsis,
  );

  /// Used for hints placed inside a [TextField]
  static final hints = base(
    fontSize: 18,
    fontWeight: FontWeight.w500,
    color: AppColors.secondary,
  );

  /// Used to give a hint of what element might do.
  static final label = base(
    fontSize: 12,
    fontWeight: FontWeight.w500,
    color: const Color(0x60000000),
    height: 16 / 12,
  );
}
